<!-- BEMACASH-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_bemacash"] } } }; !!zE && zE(() => {$zopim(() => {$zopim.livechat.set({language: "pt-BR",});$zopim.livechat.departments.filter("Bemacash");$zopim.livechat.departments.setVisitorDepartment("Bemacash");});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!-- Manufatura -->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_fly01_manufatura"] } } }; !!zE && zE(() => {$zopim(() => {$zopim.livechat.set({language: "pt-BR",});$zopim.livechat.departments.filter("Fly01 Manufatura");$zopim.livechat.departments.setVisitorDepartment("Fly01 Manufatura");});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!--Varejo-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_fly01_varejo"] } } }; !!zE && zE(() => {$zopim(() => {$zopim.livechat.set({language: "pt-BR",});$zopim.livechat.departments.filter("Fly01 Varejo");$zopim.livechat.departments.setVisitorDepartment("Fly01 Varejo");});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!--Gestão-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE || (function (e, t, s) { var n = window.zE = window.zEmbed = function () { n._.push(arguments) }, a = n.s = e.createElement(t), r = e.getElementsByTagName(t)[0]; n.set = function (e) { n.set._.push(e) }, n._ = [], n.set._ = [], a.async = true, a.setAttribute("charset", "utf-8"), a.src = "https://static.zdassets.com/ekr/asset_composer.js?key=" + s, n.t = +new Date, a.type = "text/javascript", r.parentNode.insertBefore(a, r) })(document, "script", "9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_fly01_gestao"] } } }; !!zE && zE(() => {$zopim(() => {$zopim.livechat.set({language: "pt-BR",});$zopim.livechat.departments.filter("Fly01 Gestão");$zopim.livechat.departments.setVisitorDepartment("Fly01 Gestão");});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->