<!- Scripts corrigidos para chamadas do zopim no portal do Droz->
<!--BEMACASH-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_bemacash"] } } }; !!zE && zE(() => {$zopim(function () {$zopim.livechat.clearAll();$zopim.livechat.departments.filter(1817665175);$zopim.livechat.departments.setVisitorDepartment(1817665175);$zopim.livechat.addTags("chat_bemacash","chat_origem_fly01");$zopim.livechat.theme.reload()});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!--Manufatura-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_bemacash"] } } }; !!zE && zE(() => {$zopim(function () {$zopim.livechat.clearAll();$zopim.livechat.departments.filter(1817691171);$zopim.livechat.departments.setVisitorDepartment(1817691171);$zopim.livechat.addTags("chat_fly01_manufatura","chat_origem_fly01");$zopim.livechat.theme.reload()});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!--Varejo-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_bemacash"] } } }; !!zE && zE(() => {$zopim(function () {$zopim.livechat.clearAll();$zopim.livechat.departments.filter(1817691565);$zopim.livechat.departments.setVisitorDepartment(1817691565);$zopim.livechat.addTags("chat_fly01_varejo","chat_origem_fly01");$zopim.livechat.theme.reload()});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->

<!--Gestão-->
<!-- Start of totvssuporte Zendesk Widget script -->
<script>/*<![CDATA[*/window.zE||(function(e,t,s){var n=window.zE=window.zEmbed=function(){n._.push(arguments)}, a=n.s=e.createElement(t),r=e.getElementsByTagName(t)[0];n.set=function(e){ n.set._.push(e)},n._=[],n.set._=[],a.async=true,a.setAttribute("charset","utf-8"), a.src="https://static.zdassets.com/ekr/asset_composer.js?key="+s, n.t=+new Date,a.type="text/javascript",r.parentNode.insertBefore(a,r)})(document,"script","9c45e410-744f-4aae-be0f-e7038becfe17");window.zESettings = { webWidget: { position: { horizontal: "left", vertical: "bottom" }, contactForm: { tags: ["chat_bemacash"] } } }; !!zE && zE(() => {$zopim(function () {$zopim.livechat.clearAll();$zopim.livechat.departments.filter(2147509945);$zopim.livechat.departments.setVisitorDepartment(2147509945);$zopim.livechat.addTags("chat_fly01_gestao","chat_origem_fly01");$zopim.livechat.theme.reload()});zE.show();});/*]]>*/</script>
<!-- End of totvssuporte Zendesk Widget script -->